### PR TITLE
Add retries to download file function

### PR DESCRIPTION
**Pull request by asafyehezkel**
This pr makes `download_file` function use the retries mechanism as well over `curl/wget` commands

Tested by the script below (change `VAR_DIR` path if you want to run too) plus local installation

```bash
#!/bin/bash

set -euo pipefail

RETRIES=5
REQUEST_TIMEOUT=10
RETRY_DELAY=0
HTTP_GET="curl -sL --fail --max-time $REQUEST_TIMEOUT --retry $RETRIES --retry-delay $RETRY_DELAY"
WGET="wget -q -O- --timeout=$REQUEST_TIMEOUT --tries=$RETRIES --wait=$RETRY_DELAY"

VAR_DIR='/Users/asafyehezkel/Desktop/installation'

function download_file_curl() {
  echo 'Downloading file using curl'
  $HTTP_GET $1 '-o' $2
  echo 'Downloaded file using curl'
}

function download_file_wget() {
  echo 'Downloading file using wget'
  $WGET '-O' $2 $1
  echo 'Downloaded file using wget'
}


echo 'Downloading config files by wget...'
download_file_wget https://raw.githubusercontent.com/tensorleap/helm-charts/master/config/k3d-config.yaml $VAR_DIR/k3d-config.yaml

echo 'Downloading config files by curl...'
download_file_curl https://raw.githubusercontent.com/tensorleap/helm-charts/master/config/k3d-entrypoint.sh $VAR_DIR/k3d-entrypoint.sh
```

### CODE REVIEW

**Comment by arikmaor** [comment]
The script in the PR description doesn't test curl

**Comment by asafyehezkel** [comment]
> The script in the PR description doesn't test curl

This is an example of how I test it, doesn’t meant be in the repo

Of course, you need to change `download_file_wget` to `download_file_curl`. you can do whatever you want dude :)

**Comment by arikmaor** [comment]
Just wanted to make sure you did check it :)

**Review by arikmaor — APPROVED** [review]
LGTM

Why do you need to put `''` around the parameters?

**Pull request merged**
